[2024-09-12T09:31:53.752+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T09:31:53.780+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v23.insert_inventory_data manual__2024-09-12T09:28:48.570605+00:00 [queued]>
[2024-09-12T09:31:53.798+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v23.insert_inventory_data manual__2024-09-12T09:28:48.570605+00:00 [queued]>
[2024-09-12T09:31:53.799+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-12T09:31:53.840+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_inventory_data> on 2024-09-12 09:28:48.570605+00:00
[2024-09-12T09:31:53.860+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T09:31:53.867+0000] {standard_task_runner.py:72} INFO - Started process 2242 to run task
[2024-09-12T09:31:53.864+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v23', 'insert_inventory_data', 'manual__2024-09-12T09:28:48.570605+00:00', '--job-id', '498', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp97fi1ffo']
[2024-09-12T09:31:53.871+0000] {standard_task_runner.py:105} INFO - Job 498: Subtask insert_inventory_data
[2024-09-12T09:31:53.956+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v23.insert_inventory_data manual__2024-09-12T09:28:48.570605+00:00 [running]> on host 72ac4976c45d
[2024-09-12T09:31:54.091+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v23' AIRFLOW_CTX_TASK_ID='insert_inventory_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T09:28:48.570605+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T09:28:48.570605+00:00'
[2024-09-12T09:31:54.092+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T09:31:54.108+0000] {sql.py:266} INFO - Executing: 
            TRUNCATE TABLE inventory;
            COPY inventory(id, name, stock_quantity, price)
            FROM '/shared/inventory.csv'
            DELIMITER ',' CSV HEADER;
        
[2024-09-12T09:31:54.146+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-12T09:31:54.245+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-12T09:31:54.260+0000] {sql.py:509} INFO - Running statement: 
            TRUNCATE TABLE inventory;
            COPY inventory(id, name, stock_quantity, price)
            FROM '/shared/inventory.csv'
            DELIMITER ',' CSV HEADER;
        , parameters: None
[2024-09-12T09:31:54.303+0000] {sql.py:518} INFO - Rows affected: 500
[2024-09-12T09:31:54.424+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T09:31:54.426+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag_v23, task_id=insert_inventory_data, run_id=manual__2024-09-12T09:28:48.570605+00:00, execution_date=20240912T092848, start_date=20240912T093153, end_date=20240912T093154
[2024-09-12T09:31:54.489+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T09:31:54.512+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T09:31:54.514+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
