[2024-09-11T09:50:43.840+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T09:50:43.864+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v10.update_inventory_data scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-11T09:50:43.881+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v10.update_inventory_data scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-11T09:50:43.882+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-11T09:50:43.925+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): update_inventory_data> on 2024-09-07 00:00:00+00:00
[2024-09-11T09:50:43.953+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v10', 'update_inventory_data', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp1j_z6029']
[2024-09-11T09:50:43.964+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3295) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T09:50:43.966+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask update_inventory_data
[2024-09-11T09:50:43.974+0000] {standard_task_runner.py:72} INFO - Started process 3300 to run task
[2024-09-11T09:50:44.210+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v10.update_inventory_data scheduled__2024-09-07T00:00:00+00:00 [running]> on host 4118525cd54b
[2024-09-11T09:50:44.374+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v10' AIRFLOW_CTX_TASK_ID='update_inventory_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-09-11T09:50:44.375+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T09:50:44.432+0000] {logging_mixin.py:190} INFO - Inventory updated successfully!
[2024-09-11T09:50:44.433+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-11T09:50:44.452+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T09:50:44.453+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag_v10, task_id=update_inventory_data, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20240911T095043, end_date=20240911T095044
[2024-09-11T09:50:44.507+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-11T09:50:44.532+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T09:50:44.534+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
