[2024-09-09T09:14:48.958+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-09T09:14:48.981+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v8.load_inventory_data manual__2024-09-09T09:14:07.584252+00:00 [queued]>
[2024-09-09T09:14:49.004+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v8.load_inventory_data manual__2024-09-09T09:14:07.584252+00:00 [queued]>
[2024-09-09T09:14:49.005+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-09T09:14:49.050+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_inventory_data> on 2024-09-09 09:14:07.584252+00:00
[2024-09-09T09:14:49.063+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=967) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-09T09:14:49.066+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v8', 'load_inventory_data', 'manual__2024-09-09T09:14:07.584252+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpcirdfqpx']
[2024-09-09T09:14:49.068+0000] {standard_task_runner.py:72} INFO - Started process 972 to run task
[2024-09-09T09:14:49.068+0000] {standard_task_runner.py:105} INFO - Job 56: Subtask load_inventory_data
[2024-09-09T09:14:49.186+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v8.load_inventory_data manual__2024-09-09T09:14:07.584252+00:00 [running]> on host 4118525cd54b
[2024-09-09T09:14:49.484+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v8' AIRFLOW_CTX_TASK_ID='load_inventory_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T09:14:07.584252+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T09:14:07.584252+00:00'
[2024-09-09T09:14:49.485+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-09T09:14:49.507+0000] {logging_mixin.py:190} INFO - Inventory data processing complete!
[2024-09-09T09:14:49.508+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-09T09:14:49.527+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-09T09:14:49.528+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag_v8, task_id=load_inventory_data, run_id=manual__2024-09-09T09:14:07.584252+00:00, execution_date=20240909T091407, start_date=20240909T091448, end_date=20240909T091449
[2024-09-09T09:14:49.604+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-09T09:14:49.668+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-09T09:14:49.671+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
