[2024-09-23T02:14:53.379+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-23T02:14:53.428+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v45.insert_orders_data scheduled__2024-09-22T00:00:00+00:00 [queued]>
[2024-09-23T02:14:53.459+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v45.insert_orders_data scheduled__2024-09-22T00:00:00+00:00 [queued]>
[2024-09-23T02:14:53.460+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-23T02:14:53.535+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_orders_data> on 2024-09-22 00:00:00+00:00
[2024-09-23T02:14:53.558+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v45', 'insert_orders_data', 'scheduled__2024-09-22T00:00:00+00:00', '--job-id', '1668', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpsod03fkw']
[2024-09-23T02:14:53.564+0000] {standard_task_runner.py:105} INFO - Job 1668: Subtask insert_orders_data
[2024-09-23T02:14:53.565+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9373) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-23T02:14:53.567+0000] {standard_task_runner.py:72} INFO - Started process 9378 to run task
[2024-09-23T02:14:53.763+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v45.insert_orders_data scheduled__2024-09-22T00:00:00+00:00 [running]> on host 217a74bc1b7d
[2024-09-23T02:14:54.026+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v45' AIRFLOW_CTX_TASK_ID='insert_orders_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-22T00:00:00+00:00'
[2024-09-23T02:14:54.029+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-23T02:14:54.070+0000] {sql.py:266} INFO - Executing: 
            TRUNCATE TABLE orders;
            COPY orders(id, customer_id, product_id, order_date, quantity)
            FROM '/shared/orders.csv'
            DELIMITER ',' CSV HEADER;
        
[2024-09-23T02:14:54.120+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-23T02:14:54.378+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-23T02:14:54.412+0000] {sql.py:509} INFO - Running statement: 
            TRUNCATE TABLE orders;
            COPY orders(id, customer_id, product_id, order_date, quantity)
            FROM '/shared/orders.csv'
            DELIMITER ',' CSV HEADER;
        , parameters: None
[2024-09-23T02:14:54.466+0000] {sql.py:518} INFO - Rows affected: 90
[2024-09-23T02:14:54.557+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-23T02:14:54.560+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag_v45, task_id=insert_orders_data, run_id=scheduled__2024-09-22T00:00:00+00:00, execution_date=20240922T000000, start_date=20240923T021453, end_date=20240923T021454
[2024-09-23T02:14:55.360+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-23T02:14:55.500+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-23T02:14:55.520+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
