[2024-09-11T09:46:33.717+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T09:46:33.744+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v9.extract_api_data manual__2024-09-11T09:46:14.099937+00:00 [queued]>
[2024-09-11T09:46:33.772+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v9.extract_api_data manual__2024-09-11T09:46:14.099937+00:00 [queued]>
[2024-09-11T09:46:33.773+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-11T09:46:33.817+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_api_data> on 2024-09-11 09:46:14.099937+00:00
[2024-09-11T09:46:33.845+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3130) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T09:46:33.846+0000] {standard_task_runner.py:72} INFO - Started process 3135 to run task
[2024-09-11T09:46:33.843+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v9', 'extract_api_data', 'manual__2024-09-11T09:46:14.099937+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmptlxxar8j']
[2024-09-11T09:46:33.847+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask extract_api_data
[2024-09-11T09:46:33.933+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v9.extract_api_data manual__2024-09-11T09:46:14.099937+00:00 [running]> on host 4118525cd54b
[2024-09-11T09:46:34.060+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v9' AIRFLOW_CTX_TASK_ID='extract_api_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T09:46:14.099937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T09:46:14.099937+00:00'
[2024-09-11T09:46:34.061+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T09:46:35.194+0000] {logging_mixin.py:190} INFO - It's successful!
[2024-09-11T09:46:35.195+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-11T09:46:35.209+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T09:46:35.209+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag_v9, task_id=extract_api_data, run_id=manual__2024-09-11T09:46:14.099937+00:00, execution_date=20240911T094614, start_date=20240911T094633, end_date=20240911T094635
[2024-09-11T09:46:35.269+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-11T09:46:35.314+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-11T09:46:35.326+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
