[2024-09-11T09:51:24.154+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T09:51:24.172+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v10.update_inventory_data scheduled__2024-09-10T00:00:00+00:00 [queued]>
[2024-09-11T09:51:24.186+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v10.update_inventory_data scheduled__2024-09-10T00:00:00+00:00 [queued]>
[2024-09-11T09:51:24.187+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-11T09:51:24.218+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): update_inventory_data> on 2024-09-10 00:00:00+00:00
[2024-09-11T09:51:24.226+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v10', 'update_inventory_data', 'scheduled__2024-09-10T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp0se4h8xx']
[2024-09-11T09:51:24.230+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3346) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T09:51:24.231+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask update_inventory_data
[2024-09-11T09:51:24.231+0000] {standard_task_runner.py:72} INFO - Started process 3351 to run task
[2024-09-11T09:51:24.309+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v10.update_inventory_data scheduled__2024-09-10T00:00:00+00:00 [running]> on host 4118525cd54b
[2024-09-11T09:51:24.421+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v10' AIRFLOW_CTX_TASK_ID='update_inventory_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-10T00:00:00+00:00'
[2024-09-11T09:51:24.423+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T09:51:24.450+0000] {logging_mixin.py:190} INFO - Inventory updated successfully!
[2024-09-11T09:51:24.451+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-11T09:51:24.467+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T09:51:24.467+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag_v10, task_id=update_inventory_data, run_id=scheduled__2024-09-10T00:00:00+00:00, execution_date=20240910T000000, start_date=20240911T095124, end_date=20240911T095124
[2024-09-11T09:51:24.529+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-11T09:51:24.552+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T09:51:24.554+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
