[2024-09-09T08:58:05.291+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-09T08:58:05.315+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v6.load_inventory_data manual__2024-09-09T08:57:10.004165+00:00 [queued]>
[2024-09-09T08:58:05.332+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v6.load_inventory_data manual__2024-09-09T08:57:10.004165+00:00 [queued]>
[2024-09-09T08:58:05.333+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-09T08:58:05.370+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_inventory_data> on 2024-09-09 08:57:10.004165+00:00
[2024-09-09T08:58:05.391+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=709) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-09T08:58:05.392+0000] {standard_task_runner.py:72} INFO - Started process 714 to run task
[2024-09-09T08:58:05.430+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v6', 'load_inventory_data', 'manual__2024-09-09T08:57:10.004165+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpv8p0vxfd']
[2024-09-09T08:58:05.438+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask load_inventory_data
[2024-09-09T08:58:05.550+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v6.load_inventory_data manual__2024-09-09T08:57:10.004165+00:00 [running]> on host 4118525cd54b
[2024-09-09T08:58:05.736+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v6' AIRFLOW_CTX_TASK_ID='load_inventory_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T08:57:10.004165+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T08:57:10.004165+00:00'
[2024-09-09T08:58:05.740+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-09T08:58:05.774+0000] {logging_mixin.py:190} INFO - It's moved!
[2024-09-09T08:58:05.776+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-09T08:58:05.788+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-09T08:58:05.790+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag_v6, task_id=load_inventory_data, run_id=manual__2024-09-09T08:57:10.004165+00:00, execution_date=20240909T085710, start_date=20240909T085805, end_date=20240909T085805
[2024-09-09T08:58:05.860+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-09T08:58:05.884+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-09T08:58:05.886+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
