[2024-09-20T23:21:48.866+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T23:21:48.912+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v45.insert_orders_data manual__2024-09-20T23:12:06.779286+00:00 [queued]>
[2024-09-20T23:21:48.946+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v45.insert_orders_data manual__2024-09-20T23:12:06.779286+00:00 [queued]>
[2024-09-20T23:21:48.952+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-20T23:21:49.035+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_orders_data> on 2024-09-20 23:12:06.779286+00:00
[2024-09-20T23:21:49.050+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v45', 'insert_orders_data', 'manual__2024-09-20T23:12:06.779286+00:00', '--job-id', '1638', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpaxjwl95o']
[2024-09-20T23:21:49.053+0000] {standard_task_runner.py:105} INFO - Job 1638: Subtask insert_orders_data
[2024-09-20T23:21:49.058+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6201) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-20T23:21:49.060+0000] {standard_task_runner.py:72} INFO - Started process 6206 to run task
[2024-09-20T23:21:49.440+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v45.insert_orders_data manual__2024-09-20T23:12:06.779286+00:00 [running]> on host 217a74bc1b7d
[2024-09-20T23:21:49.832+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v45' AIRFLOW_CTX_TASK_ID='insert_orders_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T23:12:06.779286+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-20T23:12:06.779286+00:00'
[2024-09-20T23:21:49.834+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T23:21:49.872+0000] {sql.py:266} INFO - Executing: 
            TRUNCATE TABLE orders;
            COPY orders(id, customer_id, product_id, order_date, quantity)
            FROM '/shared/orders.csv'
            DELIMITER ',' CSV HEADER;
        
[2024-09-20T23:21:49.898+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-20T23:21:50.110+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-20T23:21:50.169+0000] {sql.py:509} INFO - Running statement: 
            TRUNCATE TABLE orders;
            COPY orders(id, customer_id, product_id, order_date, quantity)
            FROM '/shared/orders.csv'
            DELIMITER ',' CSV HEADER;
        , parameters: None
[2024-09-20T23:21:50.207+0000] {sql.py:518} INFO - Rows affected: 50
[2024-09-20T23:21:50.244+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T23:21:50.245+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag_v45, task_id=insert_orders_data, run_id=manual__2024-09-20T23:12:06.779286+00:00, execution_date=20240920T231206, start_date=20240920T232148, end_date=20240920T232150
[2024-09-20T23:21:50.365+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-20T23:21:50.420+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T23:21:50.425+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
